export type ConfigType = {
	isGrouped: boolean;
	useRawData: boolean;
	isConfigChanged: boolean;
	showNodeLabels: boolean;
	showLinkLabels: boolean;
};
export type GraphElementsType = {
	nodes: any;
	nodeLabels: any;
	links: any;
	linkLabels: any;
	groups: any;
};
export type GraphDataType = {
	nodes: any;
	links: any;
	groups: any;
	groupLinks: any;
};
export type Node = {
	id: string;
};
export type Link = {
	source: string;
	target: string;
};
export type Group = {
	id: string;
	leaves: string[];
	color: string;
};

export type RawEdge = {
	data: RawEdgeData;
};

// enum RawEdgeDataLabel {
// 	CONTAINS = 'contains',
// 	CONSTRUCT = 'construct',
// 	HOLDS = 'holds',
// 	CALLS = 'calls',
// 	ACCEPTS = 'accepts',
// 	SPECIALIZES = 'specializes',
// 	RETURNS = 'returns',
// 	ACCESSES = 'accesses'
// }
export type RawEdgeData = {
	id: string;
	source: string;
	target: string;
	label: string;
	properties: RawEdgeDataProperties;
};
export type RawEdgeDataProperties = {
	weight: number;
	containmentType?: string;
};

export type RawGraphData = {
	elements: RawGraphDataElements;
};
export type RawGraphDataElements = {
	nodes: RawNode[];
	edges: RawEdge[];
};
export type RawNode = {
	data: RawNodeData;
};
export type RawNodeData = {
	id: string;
	labels: string[];
	properties: RawNodeDataProperties;
};
export type RawNodeDataProperties = {
	simpleName: string;
	kind?: string;
};

let test = [
	{
		id: 'CH.ifa.draw.standard',
		leaves: [
			'CH.ifa.draw.standard.FigureTransferCommand',
			'CH.ifa.draw.standard.SelectionTool',
			'CH.ifa.draw.standard.NullHandle',
			'CH.ifa.draw.standard.ChopBoxConnector',
			'CH.ifa.draw.standard.LocatorConnector',
			'CH.ifa.draw.standard.NorthHandle',
			'CH.ifa.draw.standard.AbstractConnector',
			'CH.ifa.draw.standard.CutCommand',
			'CH.ifa.draw.standard.GridConstrainer',
			'CH.ifa.draw.standard.DecoratorFigure',
			'CH.ifa.draw.standard.DragTracker',
			'CH.ifa.draw.standard.TextHolder',
			'CH.ifa.draw.standard.PasteCommand',
			'CH.ifa.draw.standard.SendToBackCommand',
			'CH.ifa.draw.standard.RelativeLocator',
			'CH.ifa.draw.standard.SouthEastHandle',
			'CH.ifa.draw.standard.ChangeAttributeCommand',
			'CH.ifa.draw.standard.BringToFrontCommand',
			'CH.ifa.draw.standard.SelectAreaTracker',
			'CH.ifa.draw.standard.NorthWestHandle',
			'CH.ifa.draw.standard.ChangeConnectionStartHandle',
			'CH.ifa.draw.standard.EastHandle',
			'CH.ifa.draw.standard.LocatorHandle',
			'CH.ifa.draw.standard.ChangeConnectionHandle',
			'CH.ifa.draw.standard.ConnectionHandle',
			'CH.ifa.draw.standard.CopyCommand',
			'CH.ifa.draw.standard.ToggleGridCommand',
			'CH.ifa.draw.standard.AbstractHandle',
			'CH.ifa.draw.standard.AbstractLocator',
			'CH.ifa.draw.standard.ChangeConnectionEndHandle',
			'CH.ifa.draw.standard.SimpleUpdateStrategy',
			'CH.ifa.draw.standard.AbstractFigure',
			'CH.ifa.draw.standard.ConnectionTool',
			'CH.ifa.draw.standard.AlignCommand',
			'CH.ifa.draw.standard.DuplicateCommand',
			'CH.ifa.draw.standard.DeleteCommand',
			'CH.ifa.draw.standard.BoxHandleKit',
			'CH.ifa.draw.standard.ToolButton',
			'CH.ifa.draw.standard.ActionTool',
			'CH.ifa.draw.standard.StandardDrawing',
			'CH.ifa.draw.standard.CreationTool',
			'CH.ifa.draw.standard.CompositeFigure',
			'CH.ifa.draw.standard.SouthHandle',
			'CH.ifa.draw.standard.WestHandle',
			'CH.ifa.draw.standard.HandleTracker',
			'CH.ifa.draw.standard.BufferedUpdateStrategy',
			'CH.ifa.draw.standard.FigureChangeEventMulticaster',
			'CH.ifa.draw.standard.OffsetLocator',
			'CH.ifa.draw.standard.ReverseFigureEnumerator',
			'CH.ifa.draw.standard.FigureEnumerator',
			'CH.ifa.draw.standard.SouthWestHandle',
			'CH.ifa.draw.standard.StandardDrawingView',
			'CH.ifa.draw.standard.AbstractTool',
			'CH.ifa.draw.standard.NorthEastHandle'
		],
		color: '#9f5cf4'
	},
	{
		id: 'CH.ifa.draw.application',
		leaves: ['CH.ifa.draw.application.DrawApplication'],
		color: '#56b961'
	},
	{
		id: 'CH.ifa.draw',
		leaves: [
			'CH.ifa.draw.contrib.PolygonScaleHandle',
			'CH.ifa.draw.contrib.DiamondFigure',
			'CH.ifa.draw.contrib.ChopPolygonConnector',
			'CH.ifa.draw.contrib.TriangleRotationHandle',
			'CH.ifa.draw.contrib.PolygonFigure',
			'CH.ifa.draw.contrib.TriangleFigure',
			'CH.ifa.draw.contrib.PolygonHandle',
			'CH.ifa.draw.contrib.PolygonTool',
			'CH.ifa.draw.util.Storable',
			'CH.ifa.draw.util.Iconkit',
			'CH.ifa.draw.util.PaletteLayout',
			'CH.ifa.draw.util.PaletteButton',
			'CH.ifa.draw.util.ReverseVectorEnumerator',
			'CH.ifa.draw.util.CommandButton',
			'CH.ifa.draw.util.FloatingTextField',
			'CH.ifa.draw.util.Filler',
			'CH.ifa.draw.util.PaletteIcon',
			'CH.ifa.draw.util.Animatable',
			'CH.ifa.draw.util.CommandMenu',
			'CH.ifa.draw.util.Command',
			'CH.ifa.draw.util.PaletteListener',
			'CH.ifa.draw.util.StorableOutput',
			'CH.ifa.draw.util.Clipboard',
			'CH.ifa.draw.util.ColorEntry',
			'CH.ifa.draw.util.StorableInput',
			'CH.ifa.draw.util.ColorMap',
			'CH.ifa.draw.util.CommandChoice',
			'CH.ifa.draw.util.Geom',
			'CH.ifa.draw.framework.Locator',
			'CH.ifa.draw.framework.FigureSelection',
			'CH.ifa.draw.framework.FigureEnumeration',
			'CH.ifa.draw.framework.PointConstrainer',
			'CH.ifa.draw.framework.Tool',
			'CH.ifa.draw.framework.HJDError',
			'CH.ifa.draw.framework.DrawingView',
			'CH.ifa.draw.framework.Figure',
			'CH.ifa.draw.framework.ConnectionFigure',
			'CH.ifa.draw.framework.DrawingChangeListener',
			'CH.ifa.draw.framework.DrawingChangeEvent',
			'CH.ifa.draw.framework.Handle',
			'CH.ifa.draw.framework.FigureChangeListener',
			'CH.ifa.draw.framework.Painter',
			'CH.ifa.draw.framework.DrawingEditor',
			'CH.ifa.draw.framework.FigureChangeEvent',
			'CH.ifa.draw.framework.Drawing',
			'CH.ifa.draw.framework.Connector',
			'CH.ifa.draw.application.DrawApplication',
			'CH.ifa.draw.samples.net',
			'CH.ifa.draw.samples.nothing',
			'CH.ifa.draw.samples.javadraw',
			'CH.ifa.draw.samples.pert',
			'CH.ifa.draw.figures.AttributeFigure',
			'CH.ifa.draw.figures.RoundRectangleFigure',
			'CH.ifa.draw.figures.GroupFigure',
			'CH.ifa.draw.figures.ScribbleTool',
			'CH.ifa.draw.figures.RadiusHandle',
			'CH.ifa.draw.figures.InsertImageCommand',
			'CH.ifa.draw.figures.BorderTool',
			'CH.ifa.draw.figures.FigureAttributes',
			'CH.ifa.draw.figures.ElbowTextLocator',
			'CH.ifa.draw.figures.ConnectedTextTool',
			'CH.ifa.draw.figures.LineConnection',
			'CH.ifa.draw.figures.ShortestDistanceConnector',
			'CH.ifa.draw.figures.TextFigure',
			'CH.ifa.draw.figures.UngroupCommand',
			'CH.ifa.draw.figures.ImageFigure',
			'CH.ifa.draw.figures.TextTool',
			'CH.ifa.draw.figures.LineFigure',
			'CH.ifa.draw.figures.EllipseFigure',
			'CH.ifa.draw.figures.ElbowHandle',
			'CH.ifa.draw.figures.BorderDecorator',
			'CH.ifa.draw.figures.ElbowConnection',
			'CH.ifa.draw.figures.PolyLineFigure',
			'CH.ifa.draw.figures.PolyLineConnector',
			'CH.ifa.draw.figures.FontSizeHandle',
			'CH.ifa.draw.figures.PolyLineHandle',
			'CH.ifa.draw.figures.ChopEllipseConnector',
			'CH.ifa.draw.figures.NumberTextFigure',
			'CH.ifa.draw.figures.RectangleFigure',
			'CH.ifa.draw.figures.PolyLineLocator',
			'CH.ifa.draw.figures.ArrowTip',
			'CH.ifa.draw.figures.GroupCommand',
			'CH.ifa.draw.figures.LineDecoration',
			'CH.ifa.draw.figures.GroupHandle',
			'CH.ifa.draw.applet.SleeperThread',
			'CH.ifa.draw.applet.DrawApplet',
			'CH.ifa.draw.standard.FigureTransferCommand',
			'CH.ifa.draw.standard.SelectionTool',
			'CH.ifa.draw.standard.NullHandle',
			'CH.ifa.draw.standard.ChopBoxConnector',
			'CH.ifa.draw.standard.LocatorConnector',
			'CH.ifa.draw.standard.NorthHandle',
			'CH.ifa.draw.standard.AbstractConnector',
			'CH.ifa.draw.standard.CutCommand',
			'CH.ifa.draw.standard.GridConstrainer',
			'CH.ifa.draw.standard.DecoratorFigure',
			'CH.ifa.draw.standard.DragTracker',
			'CH.ifa.draw.standard.TextHolder',
			'CH.ifa.draw.standard.PasteCommand',
			'CH.ifa.draw.standard.SendToBackCommand',
			'CH.ifa.draw.standard.RelativeLocator',
			'CH.ifa.draw.standard.SouthEastHandle',
			'CH.ifa.draw.standard.ChangeAttributeCommand',
			'CH.ifa.draw.standard.BringToFrontCommand',
			'CH.ifa.draw.standard.SelectAreaTracker',
			'CH.ifa.draw.standard.NorthWestHandle',
			'CH.ifa.draw.standard.ChangeConnectionStartHandle',
			'CH.ifa.draw.standard.EastHandle',
			'CH.ifa.draw.standard.LocatorHandle',
			'CH.ifa.draw.standard.ChangeConnectionHandle',
			'CH.ifa.draw.standard.ConnectionHandle',
			'CH.ifa.draw.standard.CopyCommand',
			'CH.ifa.draw.standard.ToggleGridCommand',
			'CH.ifa.draw.standard.AbstractHandle',
			'CH.ifa.draw.standard.AbstractLocator',
			'CH.ifa.draw.standard.ChangeConnectionEndHandle',
			'CH.ifa.draw.standard.SimpleUpdateStrategy',
			'CH.ifa.draw.standard.AbstractFigure',
			'CH.ifa.draw.standard.ConnectionTool',
			'CH.ifa.draw.standard.AlignCommand',
			'CH.ifa.draw.standard.DuplicateCommand',
			'CH.ifa.draw.standard.DeleteCommand',
			'CH.ifa.draw.standard.BoxHandleKit',
			'CH.ifa.draw.standard.ToolButton',
			'CH.ifa.draw.standard.ActionTool',
			'CH.ifa.draw.standard.StandardDrawing',
			'CH.ifa.draw.standard.CreationTool',
			'CH.ifa.draw.standard.CompositeFigure',
			'CH.ifa.draw.standard.SouthHandle',
			'CH.ifa.draw.standard.WestHandle',
			'CH.ifa.draw.standard.HandleTracker',
			'CH.ifa.draw.standard.BufferedUpdateStrategy',
			'CH.ifa.draw.standard.FigureChangeEventMulticaster',
			'CH.ifa.draw.standard.OffsetLocator',
			'CH.ifa.draw.standard.ReverseFigureEnumerator',
			'CH.ifa.draw.standard.FigureEnumerator',
			'CH.ifa.draw.standard.SouthWestHandle',
			'CH.ifa.draw.standard.StandardDrawingView',
			'CH.ifa.draw.standard.AbstractTool',
			'CH.ifa.draw.standard.NorthEastHandle'
		],
		color: '#b9d34a'
	},
	{
		id: 'CH.ifa.draw.figures',
		leaves: [
			'CH.ifa.draw.figures.AttributeFigure',
			'CH.ifa.draw.figures.RoundRectangleFigure',
			'CH.ifa.draw.figures.GroupFigure',
			'CH.ifa.draw.figures.ScribbleTool',
			'CH.ifa.draw.figures.RadiusHandle',
			'CH.ifa.draw.figures.InsertImageCommand',
			'CH.ifa.draw.figures.BorderTool',
			'CH.ifa.draw.figures.FigureAttributes',
			'CH.ifa.draw.figures.ElbowTextLocator',
			'CH.ifa.draw.figures.ConnectedTextTool',
			'CH.ifa.draw.figures.LineConnection',
			'CH.ifa.draw.figures.ShortestDistanceConnector',
			'CH.ifa.draw.figures.TextFigure',
			'CH.ifa.draw.figures.UngroupCommand',
			'CH.ifa.draw.figures.ImageFigure',
			'CH.ifa.draw.figures.TextTool',
			'CH.ifa.draw.figures.LineFigure',
			'CH.ifa.draw.figures.EllipseFigure',
			'CH.ifa.draw.figures.ElbowHandle',
			'CH.ifa.draw.figures.BorderDecorator',
			'CH.ifa.draw.figures.ElbowConnection',
			'CH.ifa.draw.figures.PolyLineFigure',
			'CH.ifa.draw.figures.PolyLineConnector',
			'CH.ifa.draw.figures.FontSizeHandle',
			'CH.ifa.draw.figures.PolyLineHandle',
			'CH.ifa.draw.figures.ChopEllipseConnector',
			'CH.ifa.draw.figures.NumberTextFigure',
			'CH.ifa.draw.figures.RectangleFigure',
			'CH.ifa.draw.figures.PolyLineLocator',
			'CH.ifa.draw.figures.ArrowTip',
			'CH.ifa.draw.figures.GroupCommand',
			'CH.ifa.draw.figures.LineDecoration',
			'CH.ifa.draw.figures.GroupHandle'
		],
		color: '#592bc7'
	},
	{
		id: 'CH.ifa',
		leaves: [
			'CH.ifa.draw.contrib.PolygonScaleHandle',
			'CH.ifa.draw.contrib.DiamondFigure',
			'CH.ifa.draw.contrib.ChopPolygonConnector',
			'CH.ifa.draw.contrib.TriangleRotationHandle',
			'CH.ifa.draw.contrib.PolygonFigure',
			'CH.ifa.draw.contrib.TriangleFigure',
			'CH.ifa.draw.contrib.PolygonHandle',
			'CH.ifa.draw.contrib.PolygonTool',
			'CH.ifa.draw.util.Storable',
			'CH.ifa.draw.util.Iconkit',
			'CH.ifa.draw.util.PaletteLayout',
			'CH.ifa.draw.util.PaletteButton',
			'CH.ifa.draw.util.ReverseVectorEnumerator',
			'CH.ifa.draw.util.CommandButton',
			'CH.ifa.draw.util.FloatingTextField',
			'CH.ifa.draw.util.Filler',
			'CH.ifa.draw.util.PaletteIcon',
			'CH.ifa.draw.util.Animatable',
			'CH.ifa.draw.util.CommandMenu',
			'CH.ifa.draw.util.Command',
			'CH.ifa.draw.util.PaletteListener',
			'CH.ifa.draw.util.StorableOutput',
			'CH.ifa.draw.util.Clipboard',
			'CH.ifa.draw.util.ColorEntry',
			'CH.ifa.draw.util.StorableInput',
			'CH.ifa.draw.util.ColorMap',
			'CH.ifa.draw.util.CommandChoice',
			'CH.ifa.draw.util.Geom',
			'CH.ifa.draw.framework.Locator',
			'CH.ifa.draw.framework.FigureSelection',
			'CH.ifa.draw.framework.FigureEnumeration',
			'CH.ifa.draw.framework.PointConstrainer',
			'CH.ifa.draw.framework.Tool',
			'CH.ifa.draw.framework.HJDError',
			'CH.ifa.draw.framework.DrawingView',
			'CH.ifa.draw.framework.Figure',
			'CH.ifa.draw.framework.ConnectionFigure',
			'CH.ifa.draw.framework.DrawingChangeListener',
			'CH.ifa.draw.framework.DrawingChangeEvent',
			'CH.ifa.draw.framework.Handle',
			'CH.ifa.draw.framework.FigureChangeListener',
			'CH.ifa.draw.framework.Painter',
			'CH.ifa.draw.framework.DrawingEditor',
			'CH.ifa.draw.framework.FigureChangeEvent',
			'CH.ifa.draw.framework.Drawing',
			'CH.ifa.draw.framework.Connector',
			'CH.ifa.draw.application.DrawApplication',
			'CH.ifa.draw.samples.net',
			'CH.ifa.draw.samples.nothing',
			'CH.ifa.draw.samples.javadraw',
			'CH.ifa.draw.samples.pert',
			'CH.ifa.draw.figures.AttributeFigure',
			'CH.ifa.draw.figures.RoundRectangleFigure',
			'CH.ifa.draw.figures.GroupFigure',
			'CH.ifa.draw.figures.ScribbleTool',
			'CH.ifa.draw.figures.RadiusHandle',
			'CH.ifa.draw.figures.InsertImageCommand',
			'CH.ifa.draw.figures.BorderTool',
			'CH.ifa.draw.figures.FigureAttributes',
			'CH.ifa.draw.figures.ElbowTextLocator',
			'CH.ifa.draw.figures.ConnectedTextTool',
			'CH.ifa.draw.figures.LineConnection',
			'CH.ifa.draw.figures.ShortestDistanceConnector',
			'CH.ifa.draw.figures.TextFigure',
			'CH.ifa.draw.figures.UngroupCommand',
			'CH.ifa.draw.figures.ImageFigure',
			'CH.ifa.draw.figures.TextTool',
			'CH.ifa.draw.figures.LineFigure',
			'CH.ifa.draw.figures.EllipseFigure',
			'CH.ifa.draw.figures.ElbowHandle',
			'CH.ifa.draw.figures.BorderDecorator',
			'CH.ifa.draw.figures.ElbowConnection',
			'CH.ifa.draw.figures.PolyLineFigure',
			'CH.ifa.draw.figures.PolyLineConnector',
			'CH.ifa.draw.figures.FontSizeHandle',
			'CH.ifa.draw.figures.PolyLineHandle',
			'CH.ifa.draw.figures.ChopEllipseConnector',
			'CH.ifa.draw.figures.NumberTextFigure',
			'CH.ifa.draw.figures.RectangleFigure',
			'CH.ifa.draw.figures.PolyLineLocator',
			'CH.ifa.draw.figures.ArrowTip',
			'CH.ifa.draw.figures.GroupCommand',
			'CH.ifa.draw.figures.LineDecoration',
			'CH.ifa.draw.figures.GroupHandle',
			'CH.ifa.draw.applet.SleeperThread',
			'CH.ifa.draw.applet.DrawApplet',
			'CH.ifa.draw.standard.FigureTransferCommand',
			'CH.ifa.draw.standard.SelectionTool',
			'CH.ifa.draw.standard.NullHandle',
			'CH.ifa.draw.standard.ChopBoxConnector',
			'CH.ifa.draw.standard.LocatorConnector',
			'CH.ifa.draw.standard.NorthHandle',
			'CH.ifa.draw.standard.AbstractConnector',
			'CH.ifa.draw.standard.CutCommand',
			'CH.ifa.draw.standard.GridConstrainer',
			'CH.ifa.draw.standard.DecoratorFigure',
			'CH.ifa.draw.standard.DragTracker',
			'CH.ifa.draw.standard.TextHolder',
			'CH.ifa.draw.standard.PasteCommand',
			'CH.ifa.draw.standard.SendToBackCommand',
			'CH.ifa.draw.standard.RelativeLocator',
			'CH.ifa.draw.standard.SouthEastHandle',
			'CH.ifa.draw.standard.ChangeAttributeCommand',
			'CH.ifa.draw.standard.BringToFrontCommand',
			'CH.ifa.draw.standard.SelectAreaTracker',
			'CH.ifa.draw.standard.NorthWestHandle',
			'CH.ifa.draw.standard.ChangeConnectionStartHandle',
			'CH.ifa.draw.standard.EastHandle',
			'CH.ifa.draw.standard.LocatorHandle',
			'CH.ifa.draw.standard.ChangeConnectionHandle',
			'CH.ifa.draw.standard.ConnectionHandle',
			'CH.ifa.draw.standard.CopyCommand',
			'CH.ifa.draw.standard.ToggleGridCommand',
			'CH.ifa.draw.standard.AbstractHandle',
			'CH.ifa.draw.standard.AbstractLocator',
			'CH.ifa.draw.standard.ChangeConnectionEndHandle',
			'CH.ifa.draw.standard.SimpleUpdateStrategy',
			'CH.ifa.draw.standard.AbstractFigure',
			'CH.ifa.draw.standard.ConnectionTool',
			'CH.ifa.draw.standard.AlignCommand',
			'CH.ifa.draw.standard.DuplicateCommand',
			'CH.ifa.draw.standard.DeleteCommand',
			'CH.ifa.draw.standard.BoxHandleKit',
			'CH.ifa.draw.standard.ToolButton',
			'CH.ifa.draw.standard.ActionTool',
			'CH.ifa.draw.standard.StandardDrawing',
			'CH.ifa.draw.standard.CreationTool',
			'CH.ifa.draw.standard.CompositeFigure',
			'CH.ifa.draw.standard.SouthHandle',
			'CH.ifa.draw.standard.WestHandle',
			'CH.ifa.draw.standard.HandleTracker',
			'CH.ifa.draw.standard.BufferedUpdateStrategy',
			'CH.ifa.draw.standard.FigureChangeEventMulticaster',
			'CH.ifa.draw.standard.OffsetLocator',
			'CH.ifa.draw.standard.ReverseFigureEnumerator',
			'CH.ifa.draw.standard.FigureEnumerator',
			'CH.ifa.draw.standard.SouthWestHandle',
			'CH.ifa.draw.standard.StandardDrawingView',
			'CH.ifa.draw.standard.AbstractTool',
			'CH.ifa.draw.standard.NorthEastHandle'
		],
		color: '#3d855d'
	},
	{
		id: 'CH.ifa.draw.util',
		leaves: [
			'CH.ifa.draw.util.Storable',
			'CH.ifa.draw.util.Iconkit',
			'CH.ifa.draw.util.PaletteLayout',
			'CH.ifa.draw.util.PaletteButton',
			'CH.ifa.draw.util.ReverseVectorEnumerator',
			'CH.ifa.draw.util.CommandButton',
			'CH.ifa.draw.util.FloatingTextField',
			'CH.ifa.draw.util.Filler',
			'CH.ifa.draw.util.PaletteIcon',
			'CH.ifa.draw.util.Animatable',
			'CH.ifa.draw.util.CommandMenu',
			'CH.ifa.draw.util.Command',
			'CH.ifa.draw.util.PaletteListener',
			'CH.ifa.draw.util.StorableOutput',
			'CH.ifa.draw.util.Clipboard',
			'CH.ifa.draw.util.ColorEntry',
			'CH.ifa.draw.util.StorableInput',
			'CH.ifa.draw.util.ColorMap',
			'CH.ifa.draw.util.CommandChoice',
			'CH.ifa.draw.util.Geom'
		],
		color: '#df1d5a'
	},
	{
		id: 'CH.ifa.draw.samples',
		leaves: [
			'CH.ifa.draw.samples.net.NetApp',
			'CH.ifa.draw.samples.net.NodeFigure',
			'CH.ifa.draw.samples.nothing.NothingApp',
			'CH.ifa.draw.samples.nothing.NothingApplet',
			'CH.ifa.draw.samples.javadraw.URLTool',
			'CH.ifa.draw.samples.javadraw.JavaDrawApplet',
			'CH.ifa.draw.samples.javadraw.FollowURLTool',
			'CH.ifa.draw.samples.javadraw.BouncingDrawing',
			'CH.ifa.draw.samples.javadraw.PatternPainter',
			'CH.ifa.draw.samples.javadraw.Animator',
			'CH.ifa.draw.samples.javadraw.AnimationDecorator',
			'CH.ifa.draw.samples.javadraw.JavaDrawViewer',
			'CH.ifa.draw.samples.javadraw.MySelectionTool',
			'CH.ifa.draw.samples.javadraw.JavaDrawApp',
			'CH.ifa.draw.samples.pert.PertDependency',
			'CH.ifa.draw.samples.pert.PertFigureCreationTool',
			'CH.ifa.draw.samples.pert.PertApplication',
			'CH.ifa.draw.samples.pert.PertFigure',
			'CH.ifa.draw.samples.pert.PertApplet'
		],
		color: '#905ea2'
	},
	{
		id: 'CH.ifa.draw.applet',
		leaves: ['CH.ifa.draw.applet.SleeperThread', 'CH.ifa.draw.applet.DrawApplet'],
		color: '#ddac28'
	},
	{
		id: 'CH.ifa.draw.samples.pert',
		leaves: [
			'CH.ifa.draw.samples.pert.PertDependency',
			'CH.ifa.draw.samples.pert.PertFigureCreationTool',
			'CH.ifa.draw.samples.pert.PertApplication',
			'CH.ifa.draw.samples.pert.PertFigure',
			'CH.ifa.draw.samples.pert.PertApplet'
		],
		color: '#a5f1c9'
	},
	{
		id: 'CH.ifa.draw.samples.nothing',
		leaves: ['CH.ifa.draw.samples.nothing.NothingApp', 'CH.ifa.draw.samples.nothing.NothingApplet'],
		color: '#234f8a'
	},
	{
		id: 'CH.ifa.draw.samples.net',
		leaves: ['CH.ifa.draw.samples.net.NetApp', 'CH.ifa.draw.samples.net.NodeFigure'],
		color: '#46140f'
	},
	{
		id: 'CH.ifa.draw.framework',
		leaves: [
			'CH.ifa.draw.framework.Locator',
			'CH.ifa.draw.framework.FigureSelection',
			'CH.ifa.draw.framework.FigureEnumeration',
			'CH.ifa.draw.framework.PointConstrainer',
			'CH.ifa.draw.framework.Tool',
			'CH.ifa.draw.framework.HJDError',
			'CH.ifa.draw.framework.DrawingView',
			'CH.ifa.draw.framework.Figure',
			'CH.ifa.draw.framework.ConnectionFigure',
			'CH.ifa.draw.framework.DrawingChangeListener',
			'CH.ifa.draw.framework.DrawingChangeEvent',
			'CH.ifa.draw.framework.Handle',
			'CH.ifa.draw.framework.FigureChangeListener',
			'CH.ifa.draw.framework.Painter',
			'CH.ifa.draw.framework.DrawingEditor',
			'CH.ifa.draw.framework.FigureChangeEvent',
			'CH.ifa.draw.framework.Drawing',
			'CH.ifa.draw.framework.Connector'
		],
		color: '#c7724c'
	},
	{
		id: 'CH.ifa.draw.samples.javadraw',
		leaves: [
			'CH.ifa.draw.samples.javadraw.URLTool',
			'CH.ifa.draw.samples.javadraw.JavaDrawApplet',
			'CH.ifa.draw.samples.javadraw.FollowURLTool',
			'CH.ifa.draw.samples.javadraw.BouncingDrawing',
			'CH.ifa.draw.samples.javadraw.PatternPainter',
			'CH.ifa.draw.samples.javadraw.Animator',
			'CH.ifa.draw.samples.javadraw.AnimationDecorator',
			'CH.ifa.draw.samples.javadraw.JavaDrawViewer',
			'CH.ifa.draw.samples.javadraw.MySelectionTool',
			'CH.ifa.draw.samples.javadraw.JavaDrawApp'
		],
		color: '#32696f'
	},
	{
		id: 'CH',
		leaves: [
			'CH.ifa.draw.contrib.PolygonScaleHandle',
			'CH.ifa.draw.contrib.DiamondFigure',
			'CH.ifa.draw.contrib.ChopPolygonConnector',
			'CH.ifa.draw.contrib.TriangleRotationHandle',
			'CH.ifa.draw.contrib.PolygonFigure',
			'CH.ifa.draw.contrib.TriangleFigure',
			'CH.ifa.draw.contrib.PolygonHandle',
			'CH.ifa.draw.contrib.PolygonTool',
			'CH.ifa.draw.util.Storable',
			'CH.ifa.draw.util.Iconkit',
			'CH.ifa.draw.util.PaletteLayout',
			'CH.ifa.draw.util.PaletteButton',
			'CH.ifa.draw.util.ReverseVectorEnumerator',
			'CH.ifa.draw.util.CommandButton',
			'CH.ifa.draw.util.FloatingTextField',
			'CH.ifa.draw.util.Filler',
			'CH.ifa.draw.util.PaletteIcon',
			'CH.ifa.draw.util.Animatable',
			'CH.ifa.draw.util.CommandMenu',
			'CH.ifa.draw.util.Command',
			'CH.ifa.draw.util.PaletteListener',
			'CH.ifa.draw.util.StorableOutput',
			'CH.ifa.draw.util.Clipboard',
			'CH.ifa.draw.util.ColorEntry',
			'CH.ifa.draw.util.StorableInput',
			'CH.ifa.draw.util.ColorMap',
			'CH.ifa.draw.util.CommandChoice',
			'CH.ifa.draw.util.Geom',
			'CH.ifa.draw.framework.Locator',
			'CH.ifa.draw.framework.FigureSelection',
			'CH.ifa.draw.framework.FigureEnumeration',
			'CH.ifa.draw.framework.PointConstrainer',
			'CH.ifa.draw.framework.Tool',
			'CH.ifa.draw.framework.HJDError',
			'CH.ifa.draw.framework.DrawingView',
			'CH.ifa.draw.framework.Figure',
			'CH.ifa.draw.framework.ConnectionFigure',
			'CH.ifa.draw.framework.DrawingChangeListener',
			'CH.ifa.draw.framework.DrawingChangeEvent',
			'CH.ifa.draw.framework.Handle',
			'CH.ifa.draw.framework.FigureChangeListener',
			'CH.ifa.draw.framework.Painter',
			'CH.ifa.draw.framework.DrawingEditor',
			'CH.ifa.draw.framework.FigureChangeEvent',
			'CH.ifa.draw.framework.Drawing',
			'CH.ifa.draw.framework.Connector',
			'CH.ifa.draw.application.DrawApplication',
			'CH.ifa.draw.samples.net',
			'CH.ifa.draw.samples.nothing',
			'CH.ifa.draw.samples.javadraw',
			'CH.ifa.draw.samples.pert',
			'CH.ifa.draw.figures.AttributeFigure',
			'CH.ifa.draw.figures.RoundRectangleFigure',
			'CH.ifa.draw.figures.GroupFigure',
			'CH.ifa.draw.figures.ScribbleTool',
			'CH.ifa.draw.figures.RadiusHandle',
			'CH.ifa.draw.figures.InsertImageCommand',
			'CH.ifa.draw.figures.BorderTool',
			'CH.ifa.draw.figures.FigureAttributes',
			'CH.ifa.draw.figures.ElbowTextLocator',
			'CH.ifa.draw.figures.ConnectedTextTool',
			'CH.ifa.draw.figures.LineConnection',
			'CH.ifa.draw.figures.ShortestDistanceConnector',
			'CH.ifa.draw.figures.TextFigure',
			'CH.ifa.draw.figures.UngroupCommand',
			'CH.ifa.draw.figures.ImageFigure',
			'CH.ifa.draw.figures.TextTool',
			'CH.ifa.draw.figures.LineFigure',
			'CH.ifa.draw.figures.EllipseFigure',
			'CH.ifa.draw.figures.ElbowHandle',
			'CH.ifa.draw.figures.BorderDecorator',
			'CH.ifa.draw.figures.ElbowConnection',
			'CH.ifa.draw.figures.PolyLineFigure',
			'CH.ifa.draw.figures.PolyLineConnector',
			'CH.ifa.draw.figures.FontSizeHandle',
			'CH.ifa.draw.figures.PolyLineHandle',
			'CH.ifa.draw.figures.ChopEllipseConnector',
			'CH.ifa.draw.figures.NumberTextFigure',
			'CH.ifa.draw.figures.RectangleFigure',
			'CH.ifa.draw.figures.PolyLineLocator',
			'CH.ifa.draw.figures.ArrowTip',
			'CH.ifa.draw.figures.GroupCommand',
			'CH.ifa.draw.figures.LineDecoration',
			'CH.ifa.draw.figures.GroupHandle',
			'CH.ifa.draw.applet.SleeperThread',
			'CH.ifa.draw.applet.DrawApplet',
			'CH.ifa.draw.standard.FigureTransferCommand',
			'CH.ifa.draw.standard.SelectionTool',
			'CH.ifa.draw.standard.NullHandle',
			'CH.ifa.draw.standard.ChopBoxConnector',
			'CH.ifa.draw.standard.LocatorConnector',
			'CH.ifa.draw.standard.NorthHandle',
			'CH.ifa.draw.standard.AbstractConnector',
			'CH.ifa.draw.standard.CutCommand',
			'CH.ifa.draw.standard.GridConstrainer',
			'CH.ifa.draw.standard.DecoratorFigure',
			'CH.ifa.draw.standard.DragTracker',
			'CH.ifa.draw.standard.TextHolder',
			'CH.ifa.draw.standard.PasteCommand',
			'CH.ifa.draw.standard.SendToBackCommand',
			'CH.ifa.draw.standard.RelativeLocator',
			'CH.ifa.draw.standard.SouthEastHandle',
			'CH.ifa.draw.standard.ChangeAttributeCommand',
			'CH.ifa.draw.standard.BringToFrontCommand',
			'CH.ifa.draw.standard.SelectAreaTracker',
			'CH.ifa.draw.standard.NorthWestHandle',
			'CH.ifa.draw.standard.ChangeConnectionStartHandle',
			'CH.ifa.draw.standard.EastHandle',
			'CH.ifa.draw.standard.LocatorHandle',
			'CH.ifa.draw.standard.ChangeConnectionHandle',
			'CH.ifa.draw.standard.ConnectionHandle',
			'CH.ifa.draw.standard.CopyCommand',
			'CH.ifa.draw.standard.ToggleGridCommand',
			'CH.ifa.draw.standard.AbstractHandle',
			'CH.ifa.draw.standard.AbstractLocator',
			'CH.ifa.draw.standard.ChangeConnectionEndHandle',
			'CH.ifa.draw.standard.SimpleUpdateStrategy',
			'CH.ifa.draw.standard.AbstractFigure',
			'CH.ifa.draw.standard.ConnectionTool',
			'CH.ifa.draw.standard.AlignCommand',
			'CH.ifa.draw.standard.DuplicateCommand',
			'CH.ifa.draw.standard.DeleteCommand',
			'CH.ifa.draw.standard.BoxHandleKit',
			'CH.ifa.draw.standard.ToolButton',
			'CH.ifa.draw.standard.ActionTool',
			'CH.ifa.draw.standard.StandardDrawing',
			'CH.ifa.draw.standard.CreationTool',
			'CH.ifa.draw.standard.CompositeFigure',
			'CH.ifa.draw.standard.SouthHandle',
			'CH.ifa.draw.standard.WestHandle',
			'CH.ifa.draw.standard.HandleTracker',
			'CH.ifa.draw.standard.BufferedUpdateStrategy',
			'CH.ifa.draw.standard.FigureChangeEventMulticaster',
			'CH.ifa.draw.standard.OffsetLocator',
			'CH.ifa.draw.standard.ReverseFigureEnumerator',
			'CH.ifa.draw.standard.FigureEnumerator',
			'CH.ifa.draw.standard.SouthWestHandle',
			'CH.ifa.draw.standard.StandardDrawingView',
			'CH.ifa.draw.standard.AbstractTool',
			'CH.ifa.draw.standard.NorthEastHandle'
		],
		color: '#caff09'
	},
	{
		id: 'CH.ifa.draw.contrib',
		leaves: [
			'CH.ifa.draw.contrib.PolygonScaleHandle',
			'CH.ifa.draw.contrib.DiamondFigure',
			'CH.ifa.draw.contrib.ChopPolygonConnector',
			'CH.ifa.draw.contrib.TriangleRotationHandle',
			'CH.ifa.draw.contrib.PolygonFigure',
			'CH.ifa.draw.contrib.TriangleFigure',
			'CH.ifa.draw.contrib.PolygonHandle',
			'CH.ifa.draw.contrib.PolygonTool'
		],
		color: '#1d421f'
	}
];
